---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-papermc
  labels:
    role: service-config
    app: mcs
data:
  MC_RAM: "4g"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: papermc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mcs
  name: mcs
spec:
  replicas: 1
  serviceName: mcs
  selector:
    matchLabels:
      app: mcs
  template:
    metadata:
      labels:
        app: mcs
    spec:
      containers:
        - name: main
          image: etharis/minecraft
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: minecraft-papermc
          volumeMounts:
            - mountPath: /papermc
              name: papermc
          ports:
            - containerPort: 19132
              protocol: UDP
          tty: true
          stdin: true
      volumes:
      - name: papermc
        persistentVolumeClaim:
          claimName: papermc
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mcs
spec:
  selector:
    app: mcs
  ports:
    - port: 19132
      protocol: UDP
      targetPort: 19132
      nodePort: 32132
  # Use LoadBalancer if running on a provider that supports that
  #  type: LoadBalancer
  # or use NodePort on a non-managed system;
  # however, you'll need to lookup port assigned to the service
  type: NodePort
